[package]
name = "lands-testkit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
lands-core = { workspace = true }
lands-rules = { workspace = true }
ron = { workspace = true }
serde = { workspace = true, features = ["std"] }
thiserror = { workspace = true }
